#! /bin/bash

# variables
uversion=$1
creatimg=$2
rootuser=$2
creatopt="-c"
ubuntuvn="ubuntu:$uversion"
ubuntunm=$uversion-$(date +%Y%m%d-%H%M%S)

# main() starts here
if [ \( -z "$uversion" \) -o \( \( "$creatimg" != "$creatopt" \) -a  \( ! -z "$creatimg" \) -a  \( "$rootuser" != "root" \) \) ]; then
	if [ -z "$uversion" ]; then
		echo "Error: version string is empty"
	fi
	echo "usage1: ubuntu <version> [$creatopt]    //normal usage"
	echo "usage2: ubuntu <version> root    //root login"
	echo ""
	echo "  <version> : 14.04, 16.04"
	echo "  $creatopt        : if you want to force creation of another instance"
	echo ""
	echo "debug"
	echo "-----"
	echo " version          = $uversion"
	echo " image name       = $creatimg"
	echo " create option    = $creatopt"
	echo " docker img name  = $ubuntunm"
	echo " ubuntu ver str   = $ubuntuvn"
	exit 1
fi

container_id=$(docker ps -a | awk -v "x=$ubuntuvn" '{ if ($2 == x) {print $1}}')
echo $container_id

if [ \( -z "$container_id" \) -o \( "$creatimg" = "$creatopt" \) ]; then
	echo "Creating new $ubuntuvn docker image..."
	docker run -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -u $UID \
		-v /opt:/opt -v /home/$USER:/home/$USER -v /etc/passwd:/etc/passwd:ro \
		-v /etc/shadow:/etc/shadow:ro --name=$ubuntunm -it --privileged $ubuntuvn
else
	echo "Starting Ubuntu! [$container_id]"
	docker start $container_id
	echo "Attaching to $container_id!"
	if [ "$rootuser" == "root" ]; then
		docker exec -u 0 -it $container_id bash
	else
		docker attach $container_id
	fi
fi
